### ISSUE TITLE
About raydium swap

### ISSUE THREAD

**Issue by Sh1nYamamoto** [mundodigitalpros/Solana-Trading-Client#2]
I encountered an error while using Raydium. Does this mean I should swap some SOL for WSOL?

**Comment by mundodigitalpros** [comment]
> I encountered an error while using Raydium. Does this mean I should swap some SOL for WSOL?

Yes, you can go to https://jup.ag/ to swap some SOL for WSOL in order to use Raydium-related functions. I believe ChatGPT can answer these kinds of questions…

Also, if you have any questions or suggestions, please add me on Discord, and I’ll provide better guidance. This repository is just a secondary branch, and I’m not here often.

Thank you,
Renault.

**Comment by Sh1nYamamoto** [comment]
My issue has been resolved, and everything is working fine now. Your work is amazing, blessings! ～
